title: critcare.net
description: >- # this means to ignore newlines. Copies to footer, meta description, and feed.xml
  Clinical Guidelines

theme: minima
permalink: /:categories/:title/
destination: _site
baseurl: "/critcare-test"
url: https://critcare.net
google_analytics_code: G-573KSGQWF6
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
kramdown:
  auto_ids: true

defaults:
  -
    scope:
      path:            "assets/*"
    values:
      sitemap:         false
  -
    scope:
      path:            "img/*"
    values:
      sitemap:         false



