name: mkdocs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install setuptools
          pip install wheel
          pip install mkdocs
          pip install markdown-include
          pip install mkdocs-cinder

      - name: Run mkdocs
        run: mkdocs gh-deploy --force