name: parse guidelines

# Controls when the action will run.
on:
  schedule:
    - cron: '0 9-18 * * *'

  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  makelist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install setuptools
          pip install wheel
          pip install pdfminer.six
          pip install requests
          pip install mkdocs
          pip install markdown-include
          pip install mkdocs-cinder
          pip install pandas
          pip install openpyxl
          pip install pypdf
          pip install python-docx 
          pip install textract
          pip install msal
          pip install PyMuPDF
          pip install oyaml

      - name: Run build
        env:
          ONEDRIVE_CLIENT_ID: ${{ secrets.ONEDRIVE_CLIENT_ID }}
          ONEDRIVE_CLIENT_SECRET: ${{ secrets.ONEDRIVE_CLIENT_SECRET }}
          ONEDRIVE_TENANT_ID: ${{ secrets.ONEDRIVE_TENANT_ID }}
        run: |
          python .scripts/build.py

      - name: Commit pages if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff-index --quiet HEAD || git commit -m "Automatically re-generate list and index"

      - name: Push pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}








